---
- name: Get service facts
  ansible.builtin.service_facts:

- name: Backup block
  when:
    - ansible_facts.services["forgejo.service"] is defined
    - ansible_facts.services["forgejo.service"].state == "running"
    - forgejo_active_version.stdout != forgejo_version_target
  block:
    - name: Stopping forgejo before upgrade
      become: true
      ansible.builtin.systemd_service:
        name: "forgejo.service"
        state: "stopped"
      when: ansible_service_mgr == "systemd"

    - name: "Create backup directory"
      become: true
      ansible.builtin.file:
        path: "{{ forgejo_backup_location }}"
        state: "directory"
        owner: "{{ forgejo_user }}"
        group: "{{ forgejo_group }}"
        mode: "u=rwx,g=rx,o="

    - name: Backing up forgejo before upgrade
      become: true
      ansible.builtin.command:
        cmd: "sudo -u {{ forgejo_user }} {{ forgejo_full_executable_path }} dump -c {{ forgejo_configuration_path }}/gitea.ini"
        chdir: "{{ forgejo_backup_location }}"
      changed_when: true
  rescue:
    - name: Starting forgejo because backup failed
      become: true
      ansible.builtin.systemd_service:
        name: "forgejo.service"
        state: "started"
      when: ansible_service_mgr == "systemd"

    - name: Print updating error and cancel
      ansible.builtin.fail:
        msg: "failed to backup forgejo"
