---
- name: "Create forgejo Group"
  become: true
  ansible.builtin.group:
    name: "{{ forgejo_group }}"
    system: true
    state: "present"

- name: Switch shell when not using the builtin ssh server
  ansible.builtin.set_fact:
    forgejo_shell: "/bin/bash"
  when: "not forgejo_start_ssh and forgejo_shell == '/bin/false'"

- name: "Create forgejo user"
  become: true
  ansible.builtin.user:
    name: "{{ forgejo_user }}"
    comment: "forgejo user"
    group: "{{ forgejo_group }}"
    groups: "{{ forgejo_groups | default(omit) }}"
    home: "{{ forgejo_user_home }}"
    shell: "{{ forgejo_shell }}"
    system: true
