---
- name: "Create config and data directory"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ forgejo_user }}"
    group: "{{ forgejo_group }}"
    mode: "u=rwX,g=rX"
    recurse: true
  loop:
    - "{{ forgejo_user_home }}"
    - "{{ forgejo_home }}"
    - "{{ forgejo_home }}/data"
    - "{{ forgejo_custom }}"
    - "{{ forgejo_custom }}/https"
    - "{{ forgejo_custom }}/mailer"
    - "{{ forgejo_home }}/indexers"
    - "{{ forgejo_home }}/log"
    - "{{ forgejo_repository_root }}"

- name: "Create config and data directory"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ forgejo_user }}"
    group: "{{ forgejo_group }}"
    mode: "u=rwX,g=rX,o="
    recurse: true
  loop:
    - "{{ forgejo_configuration_path }}"
