---
- name: Generate forgejo SECRET_KEY if not provided
  become: true
  ansible.builtin.shell: "umask 077; {{ forgejo_full_executable_path }} generate secret SECRET_KEY > {{ forgejo_configuration_path }}/forgejo_secret_key"
  args:
    creates: "{{ forgejo_configuration_path }}/forgejo_secret_key"
  when: forgejo_secret_key | string | length == 0

- name: Read forgejo SECRET_KEY from file
  become: true
  ansible.builtin.slurp:
    src: "{{ forgejo_configuration_path }}/forgejo_secret_key"
  register: remote_secret_key
  when: forgejo_secret_key | string | length == 0

- name: Set fact forgejo_secret_key
  ansible.builtin.set_fact:
    forgejo_secret_key: "{{ remote_secret_key['content'] | b64decode }}"
  when: forgejo_secret_key | string | length == 0

- name: Generate forgejo INTERNAL_TOKEN if not provided
  become: true
  ansible.builtin.shell: "umask 077; {{ forgejo_full_executable_path }} generate secret INTERNAL_TOKEN > {{ forgejo_configuration_path }}/forgejo_internal_token"
  args:
    creates: "{{ forgejo_configuration_path }}/forgejo_internal_token"
  when: forgejo_internal_token | string | length == 0

- name: Read forgejo INTERNAL_TOKEN from file
  become: true
  ansible.builtin.slurp:
    src: "{{ forgejo_configuration_path }}/forgejo_internal_token"
  register: remote_internal_token
  when: forgejo_internal_token | string | length == 0

- name: Set fact forgejo_internal_token
  ansible.builtin.set_fact:
    forgejo_internal_token: "{{ remote_internal_token['content'] | b64decode }}"
  when: forgejo_internal_token | string | length == 0
