---
- name: Dependency block
  block:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        cache_valid_time: 3600
        update_cache: true
      register: _pre_update_apt_cache
      until: _pre_update_apt_cache is succeeded
      when:
        - ansible_pkg_mgr == "apt"

    - name: Install dependencies
      become: true
      ansible.builtin.package:
        name: "{{ forgejo_dependencies }}"
        state: present
      register: _install_dep_packages
      until: _install_dep_packages is succeeded
      retries: 5
      delay: 2

- name: Install forgejo block
  when: (not forgejo_version_check | bool) or (not ansible_check_mode and (forgejo_active_version.stdout != forgejo_version_target))
  block:
    - name: Download forgejo archive
      ansible.builtin.get_url:
        url: "{{ forgejo_dl_url | first }}"
        dest: "/tmp/{{ forgejo_filename }}"
        checksum: "sha256:{{ forgejo_checksum }}"
        mode: "0640"
      register: _download_archive
      become: false
      until: _download_archive is succeeded
      retries: 5
      delay: 2

    - name: Download forgejo asc file
      ansible.builtin.get_url:
        url: "{{ forgejo_signed_url | first }}"
        dest: "/tmp/{{ forgejo_filename }}.asc"
        mode: "0640"
      register: _download_asc
      become: false
      until: _download_asc is succeeded
      retries: 5
      delay: 2

    - name: Check forgejo gpg key
      ansible.builtin.command: "gpg --list-keys 0x{{ forgejo_gpg_key }}"
      register: _forgejo_gpg_key_status
      changed_when: false
      become: false
      failed_when: _forgejo_gpg_key_status.rc not in (0, 2)

    - name: Print gpg key status on verbosity  # noqa: H500
      ansible.builtin.debug:
        msg: "{{ _forgejo_gpg_key_status.stdout }}"
        verbosity: 1

    - name: Gpg key
      block:
        - name: Import forgejo gpg key
          ansible.builtin.command: "gpg --keyserver {{ forgejo_gpg_server }} --recv {{ forgejo_gpg_key }}"
          register: _forgejo_import_key
          become: false
          changed_when: '"imported: 1" in _forgejo_import_key.stderr'
          # when: '_forgejo_gpg_key_status.rc != 0 or "expired" in _forgejo_gpg_key_status.stdout'
      rescue:
        - name: Load local forgejo gpg key
          ansible.builtin.copy:
            src: dj3498u4hyyarh35rkjfnghbjxug6b19.asc
            dest: /tmp/
            mode: "0400"
        - name: Import local forgejo gpg key
          ansible.builtin.command: "gpg --import /tmp/dj3498u4hyyarh35rkjfnghbjxug6b19.asc"
          register: import0
          changed_when: "'imported: [1-9]+' in import0.stdout"

    - name: Check archive signature
      become: false
      ansible.builtin.command: "gpg --verify /tmp/{{ forgejo_filename }}.asc /tmp/{{ forgejo_filename }}"
      changed_when: false

    - name: Propagate forgejo binary
      become: true
      ansible.builtin.copy:
        src: "/tmp/{{ forgejo_filename }}"
        remote_src: true
        dest: "{{ forgejo_full_executable_path }}"
        mode: "0755"
        owner: root
        group: root
      notify: "systemctl restart forgejo"
