---
- name: "Setup systemd service"
  become: true
  ansible.builtin.template:
    src: "templates/forgejo.service.j2"
    dest: "{{ forgejo_systemd_path }}/forgejo.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - "Reload systemd"
    - "systemctl restart forgejo"

- name: "Reload systemd"
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
