---
- name: Generate OAuth2 JWT_SECRET if not provided
  become: true
  ansible.builtin.shell: "umask 077; {{ forgejo_full_executable_path }} generate secret JWT_SECRET > {{ forgejo_configuration_path }}/forgejo_oauth_jwt_secret"
  args:
    creates: "{{ forgejo_configuration_path }}/forgejo_oauth_jwt_secret"
  when: forgejo_oauth2_jwt_secret | length == 0

- name: Read OAuth2 JWT_SECRET from file
  become: true
  ansible.builtin.slurp:
    src: "{{ forgejo_configuration_path }}/forgejo_oauth_jwt_secret"
  register: oauth_jwt_secret
  when: forgejo_oauth2_jwt_secret | length == 0

- name: Set fact forgejo_oauth2_jwt_secret
  ansible.builtin.set_fact:
    forgejo_oauth2_jwt_secret: "{{ oauth_jwt_secret['content'] | b64decode }}"
  when: forgejo_oauth2_jwt_secret | length == 0

- name: Generate LFS JWT_SECRET if not provided
  become: true
  ansible.builtin.shell: "umask 077; {{ forgejo_full_executable_path }} generate secret JWT_SECRET > {{ forgejo_configuration_path }}/forgejo_lfs_jwt_secret"
  args:
    creates: "{{ forgejo_configuration_path }}/forgejo_lfs_jwt_secret"
  when: forgejo_lfs_jwt_secret | length == 0

- name: Read LFS JWT_SECRET from file
  become: true
  ansible.builtin.slurp:
    src: "{{ forgejo_configuration_path }}/forgejo_lfs_jwt_secret"
  register: lfs_jwt_secret
  when: forgejo_lfs_jwt_secret | length == 0

- name: Set fact forgejo_lfs_jwt_secret
  ansible.builtin.set_fact:
    forgejo_lfs_jwt_secret: "{{ lfs_jwt_secret['content'] | b64decode }}"
  when: forgejo_lfs_jwt_secret | length == 0
