---
- name: Perform optional versionscheck
  ansible.builtin.include_tasks:
    file: "versioncheck.yml"
  when: submodules_versioncheck | bool

- name: Gather installed packages for checks later on
  ansible.builtin.package_facts:
    manager: "auto"

- name: Prepare forgejo variable import
  block:
    - name: Gather vars for forgejo
      ansible.builtin.include_vars:
        file: "{{ lookup('ansible.builtin.first_found',
          forgejo_variables) }}"
  # rescue:
  #   - name: Forgejo import info
  #     ansible.builtin.fail:
  #       msg: "Only {{ gitea_supported_forks }} are supported."

- name: Gather variables for each operating system
  ansible.builtin.include_vars:
    file: "{{ lookup('ansible.builtin.first_found', forgejo_os_variables) }}"

- name: Gather versioning information
  ansible.builtin.include_tasks:
    file: "set_forgejo_version.yml"

- name: Backup forgejo before update
  ansible.builtin.include_tasks:
    file: "backup.yml"
  when: forgejo_backup_on_upgrade|bool

- name: Create forgejo user and group
  ansible.builtin.include_tasks:
    file: "create_user.yml"

- name: "Install or update forgejo"
  ansible.builtin.include_tasks:
    file: "install_forgejo.yml"

- name: Create directories
  ansible.builtin.include_tasks:
    file: "directory.yml"

- name: Setup forgejo systemd service
  ansible.builtin.include_tasks:
    file: "install_systemd.yml"
  when: ansible_service_mgr == "systemd"

- name: Generate JWT Secrets if undefined
  ansible.builtin.include_tasks:
    file: "jwt_secrets.yml"

- name: Generate forgejo secrets if undefined
  ansible.builtin.include_tasks:
    file: "forgejo_secrets.yml"

- name: Configure forgejo
  ansible.builtin.include_tasks:
    file: "configure.yml"

- name: Deploy optional fail2ban rules
  ansible.builtin.include_tasks:
    file: "fail2ban.yml"
  when: forgejo_fail2ban_enabled | bool

- name: Optionally customize forgejo
  ansible.builtin.include_tasks:
    file: "customize_logo.yml"
  when: forgejo_customize_logo | bool

- name: Optionally customize footer
  ansible.builtin.include_tasks:
    file: "customize_footer.yml"
  when: forgejo_customize_footer | bool

- name: Optionally deploy public files
  ansible.builtin.include_tasks:
    file: "customize_public_files.yml"
  when: forgejo_customize_files | bool or forgejo_custom_themes is defined

- name: Optionally create local Users on git instance
  ansible.builtin.include_tasks:
    file: "local_git_users.yml"
  when: forgejo_users | length > 0
